SELECT GETDATE()--Datum och klockslag
SELECT SYSDATETIME()--Datum och klockslag

SELECT YEAR(GETDATE())--År
SELECT MONTH(GETDATE())--Månad
SELECT DAY(GETDATE())--Dagen

SELECT DATEPART( WEEK,'2025-12-10')

SELECT DATENAME(dw, '2025-12-10')--Veckodag
SET LANGUAGE swedish--Ändra i sessionen till svenska

SELECT DATEDIFF(DAY,'1999-12-31',GETDATE())

SELECT DATEADD(DAY,10000,GETDATE())

